cp lib_$1 lib_$1-bu
cp result_$1 result_$1-bu
cp conf_$1 conf_$1-bu
cp $1 $1-bu
cp $1_statistics $1_statistics-bu
cp $1_merge $1_merge-bu
cp $1_split $1_split-bu
cp $1_mem $1_mem-bu
cp $1_energy $1_energy-bu
cp $1_fu $1_fu-bu